language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - g++-5
          - libboost1.54
    env: COMPILER=g++-5
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          - boost-latest
        packages:
          - clang-3.8
          - libboost1.54
    env: COMPILER=clang++-3.8

notifications:
  email:
    on_success: never
    on_failure: never

install:
- echo ${PATH}
- ./travis.sh
- cmake --version
- export CXX=${COMPILER}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
- ./utils/buildAll.sh --jobs 2

script:
- mkdir -p build && cd build
- cmake .. && make -j4
- CTEST_OUTPUT_ON_FAILURE=1 make test
